import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="flex justify-center space-x-4 p-4 gap-5">
            <Link href="/">Home</Link> |<Link href="/about">About</Link> |
            <Link href="/news">News</Link> |<Link href="/contact">Contact</Link>{" "}
            |
          </nav>
        </header>
        {children}
        <footer className="flex justify-center p-4">
          <p>© 2023 My Next.js App</p>
        </footer>
      </body>
    </html>
  );
}
